lidar_camera_multi_calib:
  ros__parameters:
    image_path: "/home/pyh/zyb/slam/catkin_ws/rosbag2_2026_06_24-10_32_45_calib/image"
    pcd_path: "/home/pyh/zyb/slam/catkin_ws/rosbag2_2026_06_24-10_32_45_calib/lidar"
    result_path: "/home/pyh/zyb/slam/catkin_ws/rosbag2_2026_06_24-10_32_45_calib/extrinsic.txt"
    data_num: 3
    start_index: 1
    image_extension: ".png"
    camera_matrix: [919.8876953125, 0.0, 646.6534423828125,
                    0.0, 919.4791259765625, 373.4688415527344,
                    0.0, 0.0, 1.0]
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]
    calib_config_file: "/home/pyh/zyb/slam/catkin_ws/src/depd/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true
